netbox/dcim/urls.py
from django.urls import path

from extras.views import ObjectChangeLogView, ImageAttachmentEditView
from ipam.views import ServiceCreateView
from secrets.views import secret_add
from . import views
from .models import (
    Cable, ConsolePort, ConsoleServerPort, Device, DeviceRole, DeviceType, FrontPort, Interface, Manufacturer, Platform,
    PowerPort, PowerOutlet, Rack, RackGroup, RackReservation, RackRole, RearPort, Region, Site, VirtualChassis,
    InstanceRole, Instance)

app_name = 'dcim'
urlpatterns = [

    # Regions
    path(r'regions/', views.RegionListView.as_view(), name='region_list'),
    path(r'regions/add/', views.RegionCreateView.as_view(), name='region_add'),
    path(r'regions/import/', views.RegionBulkImportView.as_view(), name='region_import'),
    path(r'regions/delete/', views.RegionBulkDeleteView.as_view(), name='region_bulk_delete'),
    path(r'regions/<int:pk>/edit/', views.RegionEditView.as_view(), name='region_edit'),
    path(r'regions/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='region_changelog', kwargs={'model': Region}),

    # Sites
    path(r'sites/', views.SiteListView.as_view(), name='site_list'),
    path(r'sites/add/', views.SiteCreateView.as_view(), name='site_add'),
    path(r'sites/import/', views.SiteBulkImportView.as_view(), name='site_import'),
    path(r'sites/edit/', views.SiteBulkEditView.as_view(), name='site_bulk_edit'),
    path(r'sites/delete/', views.SiteBulkDeleteView.as_view(), name='site_bulk_delete'),
    path(r'sites/<slug:slug>/', views.SiteView.as_view(), name='site'),
    path(r'sites/<slug:slug>/edit/', views.SiteEditView.as_view(), name='site_edit'),
    path(r'sites/<slug:slug>/delete/', views.SiteDeleteView.as_view(), name='site_delete'),
    path(r'sites/<slug:slug>/changelog/', ObjectChangeLogView.as_view(), name='site_changelog', kwargs={'model': Site}),
    path(r'sites/<int:object_id>/images/add/', ImageAttachmentEditView.as_view(), name='site_add_image', kwargs={'model': Site}),

    # Rack groups
    path(r'rack-groups/', views.RackGroupListView.as_view(), name='rackgroup_list'),
    path(r'rack-groups/add/', views.RackGroupCreateView.as_view(), name='rackgroup_add'),
    path(r'rack-groups/import/', views.RackGroupBulkImportView.as_view(), name='rackgroup_import'),
    path(r'rack-groups/delete/', views.RackGroupBulkDeleteView.as_view(), name='rackgroup_bulk_delete'),
    path(r'rack-groups/<int:pk>/edit/', views.RackGroupEditView.as_view(), name='rackgroup_edit'),
    path(r'rack-groups/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='rackgroup_changelog', kwargs={'model': RackGroup}),

    # Rack roles
    path(r'rack-roles/', views.RackRoleListView.as_view(), name='rackrole_list'),
    path(r'rack-roles/add/', views.RackRoleCreateView.as_view(), name='rackrole_add'),
    path(r'rack-roles/import/', views.RackRoleBulkImportView.as_view(), name='rackrole_import'),
    path(r'rack-roles/delete/', views.RackRoleBulkDeleteView.as_view(), name='rackrole_bulk_delete'),
    path(r'rack-roles/<int:pk>/edit/', views.RackRoleEditView.as_view(), name='rackrole_edit'),
    path(r'rack-roles/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='rackrole_changelog', kwargs={'model': RackRole}),

    # Rack reservations
    path(r'rack-reservations/', views.RackReservationListView.as_view(), name='rackreservation_list'),
    path(r'rack-reservations/edit/', views.RackReservationBulkEditView.as_view(), name='rackreservation_bulk_edit'),
    path(r'rack-reservations/delete/', views.RackReservationBulkDeleteView.as_view(), name='rackreservation_bulk_delete'),
    path(r'rack-reservations/<int:pk>/edit/', views.RackReservationEditView.as_view(), name='rackreservation_edit'),
    path(r'rack-reservations/<int:pk>/delete/', views.RackReservationDeleteView.as_view(), name='rackreservation_delete'),
    path(r'rack-reservations/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='rackreservation_changelog', kwargs={'model': RackReservation}),

    # Racks
    path(r'racks/', views.RackListView.as_view(), name='rack_list'),
    path(r'rack-elevations/', views.RackElevationListView.as_view(), name='rack_elevation_list'),
    path(r'racks/add/', views.RackEditView.as_view(), name='rack_add'),
    path(r'racks/import/', views.RackBulkImportView.as_view(), name='rack_import'),
    path(r'racks/edit/', views.RackBulkEditView.as_view(), name='rack_bulk_edit'),
    path(r'racks/delete/', views.RackBulkDeleteView.as_view(), name='rack_bulk_delete'),
    path(r'racks/<int:pk>/', views.RackView.as_view(), name='rack'),
    path(r'racks/<int:pk>/edit/', views.RackEditView.as_view(), name='rack_edit'),
    path(r'racks/<int:pk>/delete/', views.RackDeleteView.as_view(), name='rack_delete'),
    path(r'racks/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='rack_changelog', kwargs={'model': Rack}),
    path(r'racks/<int:rack>/reservations/add/', views.RackReservationCreateView.as_view(), name='rack_add_reservation'),
    path(r'racks/<int:object_id>/images/add/', ImageAttachmentEditView.as_view(), name='rack_add_image', kwargs={'model': Rack}),

    # Manufacturers
    path(r'manufacturers/', views.ManufacturerListView.as_view(), name='manufacturer_list'),
    path(r'manufacturers/add/', views.ManufacturerCreateView.as_view(), name='manufacturer_add'),
    path(r'manufacturers/import/', views.ManufacturerBulkImportView.as_view(), name='manufacturer_import'),
    path(r'manufacturers/delete/', views.ManufacturerBulkDeleteView.as_view(), name='manufacturer_bulk_delete'),
    path(r'manufacturers/<slug:slug>/edit/', views.ManufacturerEditView.as_view(), name='manufacturer_edit'),
    path(r'manufacturers/<slug:slug>/changelog/', ObjectChangeLogView.as_view(), name='manufacturer_changelog', kwargs={'model': Manufacturer}),

    # Device types
    path(r'device-types/', views.DeviceTypeListView.as_view(), name='devicetype_list'),
    path(r'device-types/add/', views.DeviceTypeCreateView.as_view(), name='devicetype_add'),
    path(r'device-types/import/', views.DeviceTypeBulkImportView.as_view(), name='devicetype_import'),
    path(r'device-types/edit/', views.DeviceTypeBulkEditView.as_view(), name='devicetype_bulk_edit'),
    path(r'device-types/delete/', views.DeviceTypeBulkDeleteView.as_view(), name='devicetype_bulk_delete'),
    path(r'device-types/<int:pk>/', views.DeviceTypeView.as_view(), name='devicetype'),
    path(r'device-types/<int:pk>/edit/', views.DeviceTypeEditView.as_view(), name='devicetype_edit'),
    path(r'device-types/<int:pk>/delete/', views.DeviceTypeDeleteView.as_view(), name='devicetype_delete'),
    path(r'device-types/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='devicetype_changelog', kwargs={'model': DeviceType}),

    # Console port templates
    path(r'device-types/<int:pk>/console-ports/add/', views.ConsolePortTemplateCreateView.as_view(), name='devicetype_add_consoleport'),
    path(r'device-types/<int:pk>/console-ports/delete/', views.ConsolePortTemplateBulkDeleteView.as_view(), name='devicetype_delete_consoleport'),

    # Console server port templates
    path(r'device-types/<int:pk>/console-server-ports/add/', views.ConsoleServerPortTemplateCreateView.as_view(), name='devicetype_add_consoleserverport'),
    path(r'device-types/<int:pk>/console-server-ports/delete/', views.ConsoleServerPortTemplateBulkDeleteView.as_view(), name='devicetype_delete_consoleserverport'),

    # Power port templates
    path(r'device-types/<int:pk>/power-ports/add/', views.PowerPortTemplateCreateView.as_view(), name='devicetype_add_powerport'),
    path(r'device-types/<int:pk>/power-ports/delete/', views.PowerPortTemplateBulkDeleteView.as_view(), name='devicetype_delete_powerport'),

    # Power outlet templates
    path(r'device-types/<int:pk>/power-outlets/add/', views.PowerOutletTemplateCreateView.as_view(), name='devicetype_add_poweroutlet'),
    path(r'device-types/<int:pk>/power-outlets/delete/', views.PowerOutletTemplateBulkDeleteView.as_view(), name='devicetype_delete_poweroutlet'),

    # Interface templates
    path(r'device-types/<int:pk>/interfaces/add/', views.InterfaceTemplateCreateView.as_view(), name='devicetype_add_interface'),
    path(r'device-types/<int:pk>/interfaces/edit/', views.InterfaceTemplateBulkEditView.as_view(), name='devicetype_bulkedit_interface'),
    path(r'device-types/<int:pk>/interfaces/delete/', views.InterfaceTemplateBulkDeleteView.as_view(), name='devicetype_delete_interface'),

    # Front port templates
    path(r'device-types/<int:pk>/front-ports/add/', views.FrontPortTemplateCreateView.as_view(), name='devicetype_add_frontport'),
    path(r'device-types/<int:pk>/front-ports/delete/', views.FrontPortTemplateBulkDeleteView.as_view(), name='devicetype_delete_frontport'),

    # Rear port templates
    path(r'device-types/<int:pk>/rear-ports/add/', views.RearPortTemplateCreateView.as_view(), name='devicetype_add_rearport'),
    path(r'device-types/<int:pk>/rear-ports/delete/', views.RearPortTemplateBulkDeleteView.as_view(), name='devicetype_delete_rearport'),

    # Device bay templates
    path(r'device-types/<int:pk>/device-bays/add/', views.DeviceBayTemplateCreateView.as_view(), name='devicetype_add_devicebay'),
    path(r'device-types/<int:pk>/device-bays/delete/', views.DeviceBayTemplateBulkDeleteView.as_view(), name='devicetype_delete_devicebay'),

    # Device roles
    path(r'device-roles/', views.DeviceRoleListView.as_view(), name='devicerole_list'),
    path(r'device-roles/add/', views.DeviceRoleCreateView.as_view(), name='devicerole_add'),
    path(r'device-roles/import/', views.DeviceRoleBulkImportView.as_view(), name='devicerole_import'),
    path(r'device-roles/delete/', views.DeviceRoleBulkDeleteView.as_view(), name='devicerole_bulk_delete'),
    path(r'device-roles/<slug:slug>/edit/', views.DeviceRoleEditView.as_view(), name='devicerole_edit'),

netbox/extras/urls.py
from django.urls import path

from extras import views

app_name = 'extras'
urlpatterns = [

    # Tags
    path(r'tags/', views.TagListView.as_view(), name='tag_list'),
    path(r'tags/delete/', views.TagBulkDeleteView.as_view(), name='tag_bulk_delete'),
    path(r'tags/<slug:slug>/', views.TagView.as_view(), name='tag'),
    path(r'tags/<slug:slug>/edit/', views.TagEditView.as_view(), name='tag_edit'),
    path(r'tags/<slug:slug>/delete/', views.TagDeleteView.as_view(), name='tag_delete'),

    # Config contexts
    path(r'config-contexts/', views.ConfigContextListView.as_view(), name='configcontext_list'),
    path(r'config-contexts/add/', views.ConfigContextCreateView.as_view(), name='configcontext_add'),
    path(r'config-contexts/edit/', views.ConfigContextBulkEditView.as_view(), name='configcontext_bulk_edit'),
    path(r'config-contexts/delete/', views.ConfigContextBulkDeleteView.as_view(), name='configcontext_bulk_delete'),
    path(r'config-contexts/<int:pk>/', views.ConfigContextView.as_view(), name='configcontext'),
    path(r'config-contexts/<int:pk>/edit/', views.ConfigContextEditView.as_view(), name='configcontext_edit'),
    path(r'config-contexts/<int:pk>/delete/', views.ConfigContextDeleteView.as_view(), name='configcontext_delete'),

    # Image attachments
    path(r'image-attachments/<int:pk>/edit/', views.ImageAttachmentEditView.as_view(), name='imageattachment_edit'),
    path(r'image-attachments/<int:pk>/delete/', views.ImageAttachmentDeleteView.as_view(), name='imageattachment_delete'),

    # Reports
    path(r'reports/', views.ReportListView.as_view(), name='report_list'),
    path(r'reports/<str:name>/', views.ReportView.as_view(), name='report'),
    path(r'reports/<str:name>/run/', views.ReportRunView.as_view(), name='report_run'),

    # Change logging
    path(r'changelog/', views.ObjectChangeListView.as_view(), name='objectchange_list'),
    path(r'changelog/<int:pk>/', views.ObjectChangeView.as_view(), name='objectchange'),

]

netbox/netbox/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import path, re_path
from django.views.static import serve
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from netbox.views import APIRootView, HomeView, SearchView
from users.views import LoginView, LogoutView
from .admin import admin_site

schema_view = get_schema_view(
    openapi.Info(
        title="NetBox API",
        default_version='v2',
        description="API to access NetBox",
        terms_of_service="https://github.com/digitalocean/netbox",
        contact=openapi.Contact(email="netbox@digitalocean.com"),
        license=openapi.License(name="Apache v2 License"),
    ),
    validators=['flex', 'ssv'],
    public=True,
)

_patterns = [

    # Base views
    path(r'', HomeView.as_view(), name='home'),
    path(r'search/', SearchView.as_view(), name='search'),

    # Login/logout
    path(r'login/', LoginView.as_view(), name='login'),
    path(r'logout/', LogoutView.as_view(), name='logout'),

    # Apps
    path(r'circuits/', include('circuits.urls')),
    path(r'dcim/', include('dcim.urls')),
    path(r'extras/', include('extras.urls')),
    path(r'ipam/', include('ipam.urls')),
    path(r'secrets/', include('secrets.urls')),
    path(r'tenancy/', include('tenancy.urls')),
    path(r'user/', include('users.urls')),
    path(r'virtualization/', include('virtualization.urls')),
    path(r'service/', include('service.urls')),

    # API
    path(r'api/', APIRootView.as_view(), name='api-root'),
    path(r'api/circuits/', include('circuits.api.urls')),
    path(r'api/dcim/', include('dcim.api.urls')),
    path(r'api/extras/', include('extras.api.urls')),
    path(r'api/ipam/', include('ipam.api.urls')),
    path(r'api/secrets/', include('secrets.api.urls')),
    path(r'api/tenancy/', include('tenancy.api.urls')),
    path(r'api/virtualization/', include('virtualization.api.urls')),
    path(r'api/service/', include('service.api.urls')),
    path(r'api/docs/', schema_view.with_ui('swagger'), name='api_docs'),
    path(r'api/redoc/', schema_view.with_ui('redoc'), name='api_redocs'),
    re_path(r'^api/swagger(?P<format>.json|.yaml)$', schema_view.without_ui(), name='schema_swagger'),

    # Serving static media in Django to pipe it through LoginRequiredMiddleware
    path(r'media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),

    # Admin
    path(r'admin/', admin_site.urls),

]

if settings.WEBHOOKS_ENABLED:
    _patterns += [
        path(r'admin/webhook-backend-status/', include('django_rq.urls')),
    ]

if settings.DEBUG:
    import debug_toolbar
    _patterns += [
        path(r'__debug__/', include(debug_toolbar.urls)),
    ]

# Prepend BASE_PATH
urlpatterns = [
    path(r'{}'.format(settings.BASE_PATH), include(_patterns))
]

handler500 = 'utilities.views.server_error'

netbox/secrets/urls.py
from django.urls import path

from extras.views import ObjectChangeLogView
from . import views
from .models import Secret, SecretRole

app_name = 'secrets'
urlpatterns = [

    # Secret roles
    path(r'secret-roles/', views.SecretRoleListView.as_view(), name='secretrole_list'),
    path(r'secret-roles/add/', views.SecretRoleCreateView.as_view(), name='secretrole_add'),
    path(r'secret-roles/import/', views.SecretRoleBulkImportView.as_view(), name='secretrole_import'),
    path(r'secret-roles/delete/', views.SecretRoleBulkDeleteView.as_view(), name='secretrole_bulk_delete'),
    path(r'secret-roles/<slug:slug>/edit/', views.SecretRoleEditView.as_view(), name='secretrole_edit'),
    path(r'secret-roles/<slug:slug>/changelog/', ObjectChangeLogView.as_view(), name='secretrole_changelog', kwargs={'model': SecretRole}),

    # Secrets
    path(r'secrets/', views.SecretListView.as_view(), name='secret_list'),
    path(r'secrets/import/', views.SecretBulkImportView.as_view(), name='secret_import'),
    path(r'secrets/edit/', views.SecretBulkEditView.as_view(), name='secret_bulk_edit'),
    path(r'secrets/delete/', views.SecretBulkDeleteView.as_view(), name='secret_bulk_delete'),
    path(r'secrets/<int:pk>/', views.SecretView.as_view(), name='secret'),
    path(r'secrets/<int:pk>/edit/', views.secret_edit, name='secret_edit'),
    path(r'secrets/<int:pk>/delete/', views.SecretDeleteView.as_view(), name='secret_delete'),
    path(r'secrets/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='secret_changelog', kwargs={'model': Secret}),

]

netbox/templates/home.html
{% extends '_base.html' %}
{% load helpers %}

{% block content %}
{% include 'search_form.html' %}
<div class="row">
    <div class="col-sm-6 col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <strong>Organization</strong>
            </div>
            <div class="list-group">
                <div class="list-group-item">
                    <span class="badge pull-right">{{ stats.site_count }}</span>
                    <h4 class="list-group-item-heading"><a href="{% url 'dcim:site_list' %}">Sites</a></h4>
                    <p class="list-group-item-text text-muted">Geographic locations</p>
                </div>
                <div class="list-group-item">
                    <span class="badge pull-right">{{ stats.tenant_count }}</span>
                    <h4 class="list-group-item-heading"><a href="{% url 'tenancy:tenant_list' %}">Tenants</a></h4>
                    <p class="list-group-item-text text-muted">Customers or departments</p>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <strong>DCIM</strong>
            </div>
            <div class="list-group">
                <div class="list-group-item">
                    <span class="badge pull-right">{{ stats.rack_count }}</span>
                    <h4 class="list-group-item-heading"><a href="{% url 'dcim:rack_list' %}">Racks</a></h4>
                    <p class="list-group-item-text text-muted">Equipment racks, optionally organized by group</p>
                </div>
                <div class="list-group-item">
                    <span class="badge pull-right">{{ stats.device_count }}</span>
                    <h4 class="list-group-item-heading"><a href="{% url 'dcim:device_list' %}">Devices</a></h4>
                    <p class="list-group-item-text text-muted">Rack-mounted network equipment, servers, and other devices</p>
                </div>
                <div class="list-group-item">
                    <span class="badge pull-right">{{ stats.instance_count }}</span>
                    <h4 class="list-group-item-heading"><a href="{% url 'dcim:instance_list' %}">Instances</a></h4>
                    <p class="list-group-item-text text-muted">Virtual Objects: Bare Metals, Virtual Machines, Containers...</p>
                </div>
                <div class="list-group-item">
                    <h4 class="list-group-item-heading">Connections</h4>
                    <span class="badge pull-right">{{ stats.cable_count }}</span>
                    <p style="padding-left: 20px;"><a href="{% url 'dcim:cable_list' %}">Cables</a></p>
                    <span class="badge pull-right">{{ stats.interface_connections_count }}</span>
                    <p style="padding-left: 20px;"><a href="{% url 'dcim:interface_connections_list' %}">Interfaces</a></p>
                    <span class="badge pull-right">{{ stats.console_connections_count }}</span>
                    <p style="padding-left: 20px;"><a href="{% url 'dcim:console_connections_list' %}">Console</a></p>
                    <span class="badge pull-right">{{ stats.power_connections_count }}</span>
                    <p class="list-group-item-text" style="padding-left: 20px;"><a href="{% url 'dcim:power_connections_list' %}">Power</a></p>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <strong>Virtualization</strong>
            </div>
            <div class="list-group">
                <div class="list-group-item">
                    <span class="badge pull-right">{{ stats.cluster_count }}</span>
                    <h4 class="list-group-item-heading"><a href="{% url 'virtualization:cluster_list' %}">Clusters</a></h4>
                    <p class="list-group-item-text text-muted">Clusters of physical hosts in which VMs reside</p>
                </div>
                <div class="list-group-item">
                    <span class="badge pull-right">{{ stats.virtualmachine_count }}</span>
                    <h4 class="list-group-item-heading"><a href="{% url 'virtualization:virtualmachine_list' %}">Virtual Machines</a></h4>
                    <p class="list-group-item-text text-muted">Virtual compute instances running inside clusters</p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <strong>IPAM</strong>
            </div>
            <div class="list-group">
                <div class="list-group-item">
                    <span class="badge pull-right">{{ stats.vrf_count }}</span>
                    <h4 class="list-group-item-heading"><a href="{% url 'ipam:vrf_list' %}">VRFs</a></h4>
                    <p class="list-group-item-text text-muted">Virtual routing and forwarding tables</p>
                </div>
                <div class="list-group-item">
                    <span class="badge pull-right">{{ stats.aggregate_count }}</span>
                    <h4 class="list-group-item-heading"><a href="{% url 'ipam:aggregate_list' %}">Aggregates</a></h4>
                    <p class="list-group-item-text text-muted">Top-level IP allocations</p>
                </div>
                <div class="list-group-item">
                    <span class="badge pull-right">{{ stats.prefix_count }}</span>
                    <h4 class="list-group-item-heading"><a href="{% url 'ipam:prefix_list' %}">Prefixes</a></h4>
                    <p class="list-group-item-text text-muted">IPv4 and IPv6 network assignments</p>
                </div>
                <div class="list-group-item">
                    <span class="badge pull-right">{{ stats.ipaddress_count }}</span>
                    <h4 class="list-group-item-heading"><a href="{% url 'ipam:ipaddress_list' %}">IP Addresses</a></h4>
                    <p class="list-group-item-text text-muted">Individual IPv4 and IPv6 addresses</p>
                </div>
                <div class="list-group-item">
                    <span class="badge pull-right">{{ stats.vlan_count }}</span>
                    <h4 class="list-group-item-heading"><a href="{% url 'ipam:vlan_list' %}">VLANs</a></h4>
                    <p class="list-group-item-text text-muted">Layer two domains, identified by VLAN ID</p>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <strong>Circuits</strong>
            </div>
            <div class="list-group">
                <div class="list-group-item">
                    <span class="badge pull-right">{{ stats.provider_count }}</span>
                    <h4 class="list-group-item-heading"><a href="{% url 'circuits:provider_list' %}">Providers</a></h4>
                    <p class="list-group-item-text text-muted">Organizations which provide circuit connectivity</p>
                </div>
                <div class="list-group-item">
                    <span class="badge pull-right">{{ stats.circuit_count }}</span>
                    <h4 class="list-group-item-heading"><a href="{% url 'circuits:circuit_list' %}">Circuits</a></h4>
                    <p class="list-group-item-text text-muted">Communication links for Internet transit, peering, and other services</p>
                </div>
            </div>
        </div>
        {% if perms.secrets %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong>Secrets</strong>
                </div>
                <div class="list-group">
                    <div class="list-group-item">
                        <span class="badge pull-right">{{ stats.secret_count }}</span>
                        <h4 class="list-group-item-heading"><a href="{% url 'secrets:secret_list' %}">Secrets</a></h4>
                        <p class="list-group-item-text text-muted">Sensitive data (such as passwords) which has been stored securely</p>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
    <div class="col-sm-6 col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <strong>Global Topology Maps</strong>
            </div>
            {% if topology_maps %}
                <table class="table table-hover panel-body">
                    {% for tm in topology_maps %}
                        <tr>
                            <td><i class="fa fa-fw fa-map-o"></i> <a href="{% url 'extras-api:topologymap-render' pk=tm.pk %}" target="_blank">{{ tm }}</a></td>
                            <td>{{ tm.description }}</td>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <div class="panel-body text-muted">
                    None
                </div>
            {% endif %}
        </div>
        {% if report_results %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong>Reports</strong>
                </div>
                <table class="table table-hover panel-body">
                    {% for result in report_results %}
                        <tr>
                            <td><a href="{% url 'extras:report' name=result.report %}">{{ result.report }}</a></td>
                            <td class="text-right"><span title="{{ result.created }}">{% include 'extras/inc/report_label.html' %}</span></td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        {% endif %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <strong>Changelog</strong>
            </div>
            <div class="list-group">
                {% for change in changelog %}
                    {% with action=change.get_action_display|lower %}
                        <div class="list-group-item">
                            {% if action == 'created' %}
                                <span class="label label-success"><i class="fa fa-plus"></i></span>
                            {% elif action == 'updated' %}
                                <span class="label label-warning"><i class="fa fa-pencil"></i></span>
                            {% elif action == 'deleted' %}
                                <span class="label label-danger"><i class="fa fa-trash"></i></span>
                            {% endif %}
                            {{ change.changed_object_type.name|bettertitle }}
                            {% if change.changed_object.get_absolute_url %}
                                <a href="{{ change.changed_object.get_absolute_url }}">{{ change.changed_object }}</a>
                            {% else %}
                                {{ change.changed_object|default:change.object_repr }}
                            {% endif %}
                            <br />
                            <small>
                                <span class="text-muted">{{ change.user|default:change.user_name }} -</span>
                                <a href="{{ change.get_absolute_url }}" class="text-muted">{{ change.time|date:'SHORT_DATETIME_FORMAT' }}</a>
                            </small>
                        </div>
                    {% endwith %}
                    {% if forloop.last %}
                        <div class="list-group-item text-right">
                            <a href="{% url 'extras:objectchange_list' %}">View All Changes</a>
                        </div>
                    {% endif %}
                {% empty %}
                    <div class="list-group-item text-muted">No change history found</div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

netbox/templates/import_success.html
{% extends '_base.html' %}

{% block content %}
    <h1>{% block title %}Import Completed{% endblock %}</h1>
    {% include 'responsive_table.html' %}
    <a href="{{ request.path }}" class="btn btn-primary">
        <span class="fa fa-download" aria-hidden="true"></span>
        Import more
    </a>
    {% if return_url %}
        <a href="{{ return_url }}" class="btn btn-default">View All</a>
    {% endif %}
{% endblock %}

netbox/templates/responsive_table.html
{% load render_table from django_tables2 %}

<div class="table-responsive">
    {% render_table table 'inc/table.html' %}
</div>